name: Deploy bot

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          path: rbhopdog
      - name: Copy repo to remote
        uses: garygrossgarten/github-action-scp@release
        with:
          local: rbhopdog
          remote: rbhopdog
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          privateKey: ${{ secrets.KEY }}
      