name: Deploy bot
on:
  push:
    branches: [ master ]
jobs:
  deploy:
  name: Deploy
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          path: rbhopdog
      - name: Copy repo to remote
        uses: garygrossgarten/github-action-scp@release
        with:
          local: rbhopdog
          remote: ~/rbhopdog
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          privateKey: ${{ secrets.KEY }}
